---
name: Pod-Manual
version: 0.08_04
author:
  - 'Yanick Champoux <yanick@cpan.org>'
abstract: Aggregates several PODs into a single manual
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Pod-Manual
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yanick/pod-manual.git
requires:
  Object::InsideOut: 0
  Params::Validate: 0
  Pod::2::DocBook: 0.02
  Pod::Usage: 0
  Pod::XML: 0
  Test::More: 0
  XML::LibXML: 0
  version: 0
recommends:
  XML::XPathScript: 1.54
provides:
  Pod::Manual:
    file: lib/Pod/Manual.pm
    version: 0.08_04
  Pod::Manual::Docbook2LaTeX:
    file: lib/Pod/Manual/Docbook2LaTeX.pm
    version: 0.08_04
  Pod::Manual::PodXML2Docbook:
    file: lib/Pod/Manual/PodXML2Docbook.pm
    version: 0.08_04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
